export default  { 
    setor:[ 
       {id:1, name: 'Match Winner', pt:"Vencedor da partida", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:3, name: 'Second Half Winner', pt:"Vencedor do segundo tempo", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:5, name: 'Goals Over/Under', pt:"Golos Acima/Abaixo", valor:[{name: 'Over 0.5', pt: 'Acima 0.5'}, {name: 'Under 0.5', pt: 'Abaixo 0.5'}, {name: 'Over 1.5', pt: 'Acima 1.5'}, {name: 'Under 1.5', pt: 'Abaixo 1.5'}, {name: 'Over 2.5', pt: 'Acima 2.5'}, {name: 'Under 2.5', pt: 'Abaixo 2.5'}, {name: 'Over 3.5', pt: 'Acima 3.5'}, {name: 'Under 3.5', pt: 'Abaixo 3.5'}, {name: 'Over 4.5', pt: 'Acima 4.5'}, {name: 'Under 4.5', pt: 'Abaixo 4.5'}, {name: 'Over 5.5', pt: 'Acima 5.5'}, {name: 'Under 5.5', pt: 'Abaixo 5.5'}, {name: 'Over 6.5', pt: 'Acima 6.5'}, {name: 'Under 6.5', pt: 'Abaixo 6.5'}, {name: 'Over 7.5', pt: 'Acima 7.5'}, {name: 'Under 7.5', pt: 'Abaixo 7.5'}, ] },
       {id:6, name: 'Goals Over/Under First Half', pt:"Gols Acima/Abaixo do Primeiro Tempo", valor:[{name: 'Over 0.5', pt: 'Acima 0.5'}, {name: 'Under 0.5', pt: 'Abaixo 0.5'}, {name: 'Over 1.5', pt: 'Acima 1.5'}, {name: 'Under 1.5', pt: 'Abaixo 1.5'}, {name: 'Over 2.5', pt: 'Acima 2.5'}, {name: 'Under 2.5', pt: 'Abaixo 2.5'}, {name: 'Over 3.5', pt: 'Acima 3.5'}, {name: 'Under 3.5', pt: 'Abaixo 3.5'}, {name: 'Over 4.5', pt: 'Acima 4.5'}, {name: 'Under 4.5', pt: 'Abaixo 4.5'}, {name: 'Over 5.5', pt: 'Acima 5.5'}, {name: 'Under 5.5', pt: 'Abaixo 5.5'}, {name: 'Over 6.5', pt: 'Acima 6.5'}, {name: 'Under 6.5', pt: 'Abaixo 6.5'}, {name: 'Over 7.5', pt: 'Acima 7.5'}, {name: 'Under 7.5', pt: 'Abaixo 7.5'}, ] },
       {id:25, name: 'Goals Over/Under - Second Half', pt:"Gols Acima/Abaixo - Segundo Tempo", valor:[{name: 'Over 0.5', pt: 'Acima 0.5'}, {name: 'Under 0.5', pt: 'Abaixo 0.5'}, {name: 'Over 1.5', pt: 'Acima 1.5'}, {name: 'Under 1.5', pt: 'Abaixo 1.5'}, {name: 'Over 2.5', pt: 'Acima 2.5'}, {name: 'Under 2.5', pt: 'Abaixo 2.5'}, {name: 'Over 3.5', pt: 'Acima 3.5'}, {name: 'Under 3.5', pt: 'Abaixo 3.5'}, {name: 'Over 4.5', pt: 'Acima 4.5'}, {name: 'Under 4.5', pt: 'Abaixo 4.5'}, {name: 'Over 5.5', pt: 'Acima 5.5'}, {name: 'Under 5.5', pt: 'Abaixo 5.5'}, {name: 'Over 6.5', pt: 'Acima 6.5'}, {name: 'Under 6.5', pt: 'Abaixo 6.5'}, {name: 'Over 7.5', pt: 'Acima 7.5'}, {name: 'Under 7.5', pt: 'Abaixo 7.5'}, ] },
       {id:7, name: 'HT/FT Double', pt:"Resultado no Intervalo | Resultado Final", valor:[{name:"Home/Home", pt:"Casa/Casa"}, {name:"Draw/Home", pt:"Empate/Casa"}, {name:"Away/Home", pt:"Fora/Casa"}, {name:"Home/Draw", pt:"Casa/Empate"}, {name:"Draw/Draw", pt:"Empate/Empate"}, {name:"Away/Draw", pt:"Fora/Empate"} , {name:"Home/Away", pt:"Casa/Fora"}, {name:"Draw/Away", pt:"Empate/Fora"}, {name:"Away/Away", pt:"Fora/Fora"} ] },
       {id:27, name: 'Clean Sheet - Home', pt:"Time da Casa - Nenhum Gol Solfrido", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:28, name: 'Clean Sheet - Away', pt:"Time de Fora - Nenhum Gol Solfrido", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:8, name: 'Both Teams Score', pt:"Ambas as equipes marcam", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:10, name: 'Exact Score', pt:"Placar Exato", valor:[{name:"0:0", pt:"0x0"}, {name:"0:1", pt:"0x1"}, {name:"0:2", pt:"0x2"}, {name:"0:3", pt:"0x3"}, {name:"0:4", pt:"0x4"}, {name:"0:5", pt:"0x5"}, {name:"0:6", pt:"0x6"}, {name:"0:7", pt:"0x7"},  {name:"1:0", pt:"1x0"}, {name:"1:1", pt:"1x1"}, {name:"1:2", pt:"1x2"}, {name:"1:3", pt:"1x3"}, {name:"1:4", pt:"1x4"}, {name:"1:5", pt:"1x5"}, {name:"1:6", pt:"1x6"}, {name:"1:7", pt:"1x7"}, {name:"2:0", pt:"2x0"}, {name:"2:1", pt:"2x1"}, {name:"2:2", pt:"2x2"}, {name:"2:3", pt:"2x3"}, {name:"2:4", pt:"2x4"}, {name:"2:5", pt:"2x5"}, {name:"2:6", pt:"2x6"}, {name:"2:7", pt:"2x7"}, {name:"3:0", pt:"3x0"}, {name:"3:1", pt:"3x1"}, {name:"3:2", pt:"3x2"}, {name:"3:3", pt:"3x3"}, {name:"3:4", pt:"3x4"}, {name:"3:5", pt:"3x5"}, {name:"3:6", pt:"3x6"}, {name:"3:7", pt:"3x7"}, {name:"4:0", pt:"4x0"}, {name:"4:1", pt:"4x1"}, {name:"4:2", pt:"4x2"}, {name:"4:3", pt:"4x3"}, {name:"4:4", pt:"4x4"}, {name:"4:5", pt:"4x5"}, {name:"4:6", pt:"4x6"}, {name:"4:7", pt:"4x7"}, {name:"5:0", pt:"5x0"}, {name:"5:1", pt:"5x1"}, {name:"5:2", pt:"5x2"}, {name:"5:3", pt:"5x3"}, {name:"5:4", pt:"5x4"}, {name:"5:5", pt:"5x5"}, {name:"5:6", pt:"5x6"}, {name:"5:7", pt:"5x7"}, {name:"6:0", pt:"6x0"}, {name:"6:1", pt:"6x1"}, {name:"6:2", pt:"6x2"}, {name:"6:3", pt:"6x3"}, {name:"6:4", pt:"6x4"}, {name:"6:5", pt:"6x5"}, {name:"6:6", pt:"6x6"}, {name:"6:7", pt:"6x7"}, {name:"7:0", pt:"7x0"}, {name:"7:1", pt:"7x1"}, {name:"7:2", pt:"7x2"}, {name:"7:3", pt:"7x3"}, {name:"7:4", pt:"7x4"}, {name:"7:5", pt:"7x5"}, {name:"7:6", pt:"7x6"}, {name:"7:7", pt:"7x7"}, ] },
       {id:31, name: 'Correct Score - First Half', pt:"Resultado Exato - Primeiro Tempo", valor:[{name:"0:0", pt:"0x0"}, {name:"0:1", pt:"0x1"}, {name:"0:2", pt:"0x2"}, {name:"0:3", pt:"0x3"}, {name:"0:4", pt:"0x4"}, {name:"0:5", pt:"0x5"}, {name:"0:6", pt:"0x6"}, {name:"0:7", pt:"0x7"},  {name:"1:0", pt:"1x0"}, {name:"1:1", pt:"1x1"}, {name:"1:2", pt:"1x2"}, {name:"1:3", pt:"1x3"}, {name:"1:4", pt:"1x4"}, {name:"1:5", pt:"1x5"}, {name:"1:6", pt:"1x6"}, {name:"1:7", pt:"1x7"}, {name:"2:0", pt:"2x0"}, {name:"2:1", pt:"2x1"}, {name:"2:2", pt:"2x2"}, {name:"2:3", pt:"2x3"}, {name:"2:4", pt:"2x4"}, {name:"2:5", pt:"2x5"}, {name:"2:6", pt:"2x6"}, {name:"2:7", pt:"2x7"}, {name:"3:0", pt:"3x0"}, {name:"3:1", pt:"3x1"}, {name:"3:2", pt:"3x2"}, {name:"3:3", pt:"3x3"}, {name:"3:4", pt:"3x4"}, {name:"3:5", pt:"3x5"}, {name:"3:6", pt:"3x6"}, {name:"3:7", pt:"3x7"}, {name:"4:0", pt:"4x0"}, {name:"4:1", pt:"4x1"}, {name:"4:2", pt:"4x2"}, {name:"4:3", pt:"4x3"}, {name:"4:4", pt:"4x4"}, {name:"4:5", pt:"4x5"}, {name:"4:6", pt:"4x6"}, {name:"4:7", pt:"4x7"}, {name:"5:0", pt:"5x0"}, {name:"5:1", pt:"5x1"}, {name:"5:2", pt:"5x2"}, {name:"5:3", pt:"5x3"}, {name:"5:4", pt:"5x4"}, {name:"5:5", pt:"5x5"}, {name:"5:6", pt:"5x6"}, {name:"5:7", pt:"5x7"}, {name:"6:0", pt:"6x0"}, {name:"6:1", pt:"6x1"}, {name:"6:2", pt:"6x2"}, {name:"6:3", pt:"6x3"}, {name:"6:4", pt:"6x4"}, {name:"6:5", pt:"6x5"}, {name:"6:6", pt:"6x6"}, {name:"6:7", pt:"6x7"}, {name:"7:0", pt:"7x0"}, {name:"7:1", pt:"7x1"}, {name:"7:2", pt:"7x2"}, {name:"7:3", pt:"7x3"}, {name:"7:4", pt:"7x4"}, {name:"7:5", pt:"7x5"}, {name:"7:6", pt:"7x6"}, {name:"7:7", pt:"7x7"}, ] },
       {id:12, name: 'Double Chance', pt:"Chance dupla", valor:[{name:"Home/Home", pt:"Casa/Casa"}, {name:"Draw/Home", pt:"Empate/Casa"}, {name:"Away/Home", pt:"Fora/Casa"}, {name:"Home/Draw", pt:"Casa/Empate"}, {name:"Draw/Draw", pt:"Empate/Empate"}, {name:"Away/Draw", pt:"Fora/Empate"} , {name:"Home/Away", pt:"Casa/Fora"}, {name:"Draw/Away", pt:"Empate/Fora"}, {name:"Away/Away", pt:"Fora/Fora"} ] },
       {id:13, name: 'First Half Winner', pt:"Vencedor do primeiro tempo", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:14, name: 'Team To Score First', pt:"Equipe a marcar primeiro", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:15, name: 'Team To Score Last', pt:"Equipe a marcar por último", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:32, name: 'Win Both Halves', pt:"Ganha o 1° e 2° Tempo", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:16, name: 'Total - Home', pt:"Total de Gols Time da Casa", valor:[{name: 'Over 0.5', pt: 'Acima 0.5'}, {name: 'Under 0.5', pt: 'Abaixo 0.5'}, {name: 'Over 1.5', pt: 'Acima 1.5'}, {name: 'Under 1.5', pt: 'Abaixo 1.5'}, {name: 'Over 2.5', pt: 'Acima 2.5'}, {name: 'Under 2.5', pt: 'Abaixo 2.5'}, {name: 'Over 3.5', pt: 'Acima 3.5'}, {name: 'Under 3.5', pt: 'Abaixo 3.5'}, {name: 'Over 4.5', pt: 'Acima 4.5'}, {name: 'Under 4.5', pt: 'Abaixo 4.5'}, {name: 'Over 5.5', pt: 'Acima 5.5'}, {name: 'Under 5.5', pt: 'Abaixo 5.5'}, {name: 'Over 6.5', pt: 'Acima 6.5'}, {name: 'Under 6.5', pt: 'Abaixo 6.5'}, {name: 'Over 7.5', pt: 'Acima 7.5'}, {name: 'Under 7.5', pt: 'Abaixo 7.5'}, ] },
       {id:16, name: 'Total - Away', pt:"Total de Gols Time de Fora", valor:[{name: 'Over 0.5', pt: 'Acima 0.5'}, {name: 'Under 0.5', pt: 'Abaixo 0.5'}, {name: 'Over 1.5', pt: 'Acima 1.5'}, {name: 'Under 1.5', pt: 'Abaixo 1.5'}, {name: 'Over 2.5', pt: 'Acima 2.5'}, {name: 'Under 2.5', pt: 'Abaixo 2.5'}, {name: 'Over 3.5', pt: 'Acima 3.5'}, {name: 'Under 3.5', pt: 'Abaixo 3.5'}, {name: 'Over 4.5', pt: 'Acima 4.5'}, {name: 'Under 4.5', pt: 'Abaixo 4.5'}, {name: 'Over 5.5', pt: 'Acima 5.5'}, {name: 'Under 5.5', pt: 'Abaixo 5.5'}, {name: 'Over 6.5', pt: 'Acima 6.5'}, {name: 'Under 6.5', pt: 'Abaixo 6.5'}, {name: 'Over 7.5', pt: 'Acima 7.5'}, {name: 'Under 7.5', pt: 'Abaixo 7.5'}, ] },
       {id:20, name: 'Double Chance', pt:"Chance dupla - No Primeiro Tempo", valor:[{name:"Home/Home", pt:"Casa/Casa"}, {name:"Draw/Home", pt:"Empate/Casa"}, {name:"Away/Home", pt:"Fora/Casa"}, {name:"Home/Draw", pt:"Casa/Empate"}, {name:"Draw/Draw", pt:"Empate/Empate"}, {name:"Away/Draw", pt:"Fora/Empate"} , {name:"Home/Away", pt:"Casa/Fora"}, {name:"Draw/Away", pt:"Empate/Fora"}, {name:"Away/Away", pt:"Fora/Fora"} ] },
       {id:34, name: 'Both Teams Score - First Half', pt:"Ambas as equipes marcam - No Primeiro Tempo", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:35, name: 'Both Teams To Score - Second Half', pt:"Ambas as equipes marcam - No Segunda Tempo", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:36, name: 'Win To Nil', pt:"Ganha Sem Levar Gol", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:21, name: 'Odd/Even', pt:"Soma do Resultado Final do Jogo Impar/par", valor:[{name:"Odd", pt:"Impar"}, {name:"Even", pt:"Par"}] },
       {id:22, name: 'Odd/Even - First Half', pt:"Soma do Jogo No Primeiro Tempo Impar/par", valor:[{name:"Odd", pt:"Impar"}, {name:"Even", pt:"Par"}] },
       {id:23, name: 'Home Odd/Even', pt:"Resultado Final do Time da Casa Impar/par", valor:[{name:"Odd", pt:"Impar"}, {name:"Even", pt:"Par"}] },
       {id:60, name: 'Away Odd/Even', pt:"Resultado Final do Time de Fora Impar/par", valor:[{name:"Odd", pt:"Impar"}, {name:"Even", pt:"Par"}] },
       {id:38, name: 'Exact Goals Number', pt:"Número exato de Gols do jogo", valor:[{name:0, pt:0}, {name:1, pt:1}, {name:2, pt:2}, {name:3, pt:3}, {name:4, pt:4}, {name:5, pt:5}, {name:6, pt:6}, {name:7, pt:7}, {name:"more 7", pt:"Mais que 7"},] },
       {id:39, name: 'To Win Either Half', pt:"Ganha o 1° ou 2° Tempo", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] },
       {id:40, name: 'Home Team Exact Goals Number', pt:"Número exato de Gols/ Time da Casa", valor:[{name:0, pt:0}, {name:1, pt:1}, {name:2, pt:2}, {name:3, pt:3}, {name:"more 3", pt:"Mais que 3"},] },
       {id:41, name: 'Away Team Exact Goals Number', pt:"Número exato de Gols/Time de Fora", valor:[{name:0, pt:0}, {name:1, pt:1}, {name:2, pt:2}, {name:3, pt:3},  {name:"more 3", pt:"Mais que 3"},] },
       {id:42, name: 'Second Half Exact Goals Number', pt:"Número exato de gols do segundo tempo", valor:[{name:0, pt:0}, {name:1, pt:1}, {name:2, pt:2}, {name:3, pt:3}, {name:4, pt:4}, {name:5, pt:5}, {name:"more 5", pt:"Mais que 5"},] },
       {id:43, name: 'Home Team Score a Goal', pt:"Time da casa marca um gol", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:43, name: 'Away Team Score a Goal', pt:"Time de Fora marca um gol", valor:[{name:"Yes", pt:"Sim"}, {name:"No", pt:"Não"}] },
       {id:45, name: 'Corners Over Under', pt:"Quantidade De Escanteio", valor:[{name: 'Over 0.5', pt: 'Acima 0.5'}, {name: 'Under 0.5', pt: 'Abaixo 0.5'}, {name: 'Over 1.5', pt: 'Acima 1.5'}, {name: 'Under 1.5', pt: 'Abaixo 1.5'}, {name: 'Over 2.5', pt: 'Acima 2.5'}, {name: 'Under 2.5', pt: 'Abaixo 2.5'}, {name: 'Over 3.5', pt: 'Acima 3.5'}, {name: 'Under 3.5', pt: 'Abaixo 3.5'}, {name: 'Over 4.5', pt: 'Acima 4.5'}, {name: 'Under 4.5', pt: 'Abaixo 4.5'}, {name: 'Over 5.5', pt: 'Acima 5.5'}, {name: 'Under 5.5', pt: 'Abaixo 5.5'}, {name: 'Over 6.5', pt: 'Acima 6.5'}, {name: 'Under 6.5', pt: 'Abaixo 6.5'}, {name: 'Over 7.5', pt: 'Acima 7.5'}, {name: 'Under 7.5', pt: 'Abaixo 7.5'}, {name: 'Over 8.5', pt: 'Acima 8.5'}, {name: 'Under 8.5', pt: 'Abaixo 8.5'}, {name: 'Over 9.5', pt: 'Acima 9.5'}, {name: 'Under 9.5', pt: 'Abaixo 9.5'}, {name: 'Over 10.5', pt: 'Acima 10.5'}, {name: 'Under 10.5', pt: 'Abaixo 10.5'},  ] },
       {id:38, name: 'Exact Goals Number - First Half', pt:"Número exato de gols - primeiro tempo", valor:[{name:0, pt:0}, {name:1, pt:1}, {name:2, pt:2}, {name:3, pt:3}, {name:4, pt:4}, {name:5, pt:5},  {name:"more 5", pt:"Mais que 5"},] },
       {id:63, name: 'Odd/Even - Second Half', pt:"Resultado do Segundo Tempo Impar/par", valor:[{name:"Odd", pt:"Impar"}, {name:"Even", pt:"Par"}] },
       {id:48, name: 'To Score In Both Halves By Teams', pt:"Time que Marca no 1° e 2° Tempo", valor:[{name:"Home", pt:"Casa"}, {name:"Draw", pt:"Empate"}, {name:"Away", pt:"Fora"}] }, 





    ]
    
 };


